<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBbbIHu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBbbIHu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBbbIHu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBbbIHu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXBbbIHu\App_KernelDevDebugContainer([
    'container.build_hash' => 'XBbbIHu',
    'container.build_id' => '899fca5a',
    'container.build_time' => 1683992543,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBbbIHu');
