<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9TFbdFA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9TFbdFA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9TFbdFA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9TFbdFA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9TFbdFA\App_KernelDevDebugContainer([
    'container.build_hash' => '9TFbdFA',
    'container.build_id' => '14f245ee',
    'container.build_time' => 1681320792,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9TFbdFA');
