<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                'build/runtime.61b1725c.js',
                'build/712.d60b98d2.js',
                'build/app.1f5efffa.js',
            ],
            'css' => [
                'build/712.27b9381d.css',
                'build/app.e577f9ac.css',
            ],
        ],
    ],
],

]];
